# Generated by Django 3.1.2 on 2021-03-30 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210330_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
