# Generated by Django 3.1.2 on 2021-04-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210330_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
