# Generated by Django 3.1.2 on 2021-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_datetime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paid_datetime',
            field=models.DateField(),
        ),
    ]
